apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-on-kub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: deployment-for-kub
          image: nithin8/docker-for-kub